const ENTERTAINMENT_DATA =
{
  "meta": {
    "appName": "Entertainment Radar",
    "generated": "2026-07-11",
    "windowLabel": "July 2026 – June 2027",
    "disclaimer": "Scores are analyst estimates for ecommerce planning, compiled 2026-07-11 from public release schedules and trade reporting. Release dates shift; verify licensing status with the rights holder before committing inventory."
  },
  "weights": {
    "scale": 0.30,
    "reachability": 0.25,
    "merchability": 0.20,
    "passion": 0.15,
    "competition": 0.10
  },
  "dimensions": {
    "scale": "Size of the US fandom — how many consumers know and follow the property.",
    "reachability": "How findable the fandom is on ecommerce sites and Amazon — unique, ownable search keywords are the key signal.",
    "merchability": "How well the content translates into desirable products — brands, symbols, lifestyle, and iconography fans want to own.",
    "passion": "Fan intensity and propensity to buy, wear, collect, or gift merchandise.",
    "competition": "Market whitespace. 10 = wide-open, few products or licensees; 1 = saturated shelf. Surprise hits with low competition are the biggest opportunities."
  },
  "titles": [
    {
      "id": "minions-monsters",
      "title": "Minions & Monsters",
      "type": "Movie",
      "releaseDate": "2026-07-01",
      "releaseWindow": "July 1, 2026",
      "dateConfirmed": true,
      "platform": "Theatrical (Universal)",
      "producers": ["Illumination", "Chris Meledandri"],
      "rightsHolder": "Universal Products & Experiences",
      "franchise": "Despicable Me / Minions",
      "genre": "Animated comedy",
      "keywords": ["Minions", "Gru", "banana", "Kevin Stuart Bob"],
      "scores": { "scale": 9, "reachability": 6, "merchability": 8, "passion": 6, "competition": 3 },
      "monthSpotlight": true,
      "notes": "In theaters now. Family juggernaut; shelf already crowded with Minions product, so differentiation matters more than speed."
    },
    {
      "id": "moana-live-action",
      "title": "Moana (live action)",
      "type": "Movie",
      "releaseDate": "2026-07-10",
      "releaseWindow": "July 10, 2026",
      "dateConfirmed": true,
      "platform": "Theatrical (Disney)",
      "producers": ["Walt Disney Pictures", "Seven Bucks Productions"],
      "rightsHolder": "Disney Consumer Products",
      "franchise": "Moana",
      "genre": "Fantasy adventure",
      "keywords": ["Moana", "Maui", "Te Fiti", "ocean adventure"],
      "scores": { "scale": 8, "reachability": 7, "merchability": 8, "passion": 7, "competition": 3 },
      "monthSpotlight": true,
      "notes": "Opened this week with Dwayne Johnson as Maui. Disney licensing program is mature; watch for a summer beach/vacation merch spike."
    },
    {
      "id": "evil-dead-burn",
      "title": "Evil Dead Burn",
      "type": "Movie",
      "releaseDate": "2026-07-10",
      "releaseWindow": "July 10, 2026",
      "dateConfirmed": true,
      "platform": "Theatrical (New Line / StudioCanal)",
      "producers": ["Ghost House Pictures", "Sam Raimi", "Rob Tapert"],
      "rightsHolder": "StudioCanal / New Line (limited licensing program)",
      "franchise": "Evil Dead",
      "genre": "Horror",
      "keywords": ["Evil Dead", "Necronomicon", "Deadite", "horror collectible"],
      "scores": { "scale": 4, "reachability": 6, "merchability": 5, "passion": 7, "competition": 7 },
      "monthSpotlight": true,
      "notes": "Niche but devoted horror fandom with strong collector behavior and thin official product — a small but fast whitespace play if reviews land."
    },
    {
      "id": "the-odyssey",
      "title": "The Odyssey",
      "type": "Movie",
      "releaseDate": "2026-07-17",
      "releaseWindow": "July 17, 2026",
      "dateConfirmed": true,
      "platform": "Theatrical (Universal)",
      "producers": ["Syncopy", "Christopher Nolan", "Emma Thomas"],
      "rightsHolder": "Universal Products & Experiences (minimal program expected)",
      "franchise": "Standalone (Homer adaptation)",
      "genre": "Epic",
      "keywords": ["The Odyssey movie", "Nolan Odyssey", "Odysseus"],
      "scores": { "scale": 6, "reachability": 3, "merchability": 4, "passion": 7, "competition": 8 },
      "monthSpotlight": true,
      "notes": "The month's prestige event, but 'Odyssey' is a generic, hard-to-own keyword and Nolan films historically drive little merchandise."
    },
    {
      "id": "spiderman-brand-new-day",
      "title": "Spider-Man: Brand New Day",
      "type": "Movie",
      "releaseDate": "2026-07-31",
      "releaseWindow": "July 31, 2026",
      "dateConfirmed": true,
      "platform": "Theatrical (Sony / Columbia)",
      "producers": ["Columbia Pictures", "Marvel Studios", "Kevin Feige", "Amy Pascal"],
      "rightsHolder": "Disney Consumer Products (Marvel controls Spider-Man merchandising, not Sony)",
      "franchise": "Marvel / Spider-Man",
      "genre": "Superhero",
      "keywords": ["Spider-Man Brand New Day", "Spidey", "web slinger", "Tom Holland Spider-Man"],
      "scores": { "scale": 10, "reachability": 8, "merchability": 9, "passion": 9, "competition": 2 },
      "monthSpotlight": true,
      "notes": "The month's biggest commercial event. Enormous demand spike expected, but the licensed shelf is the most saturated in the business — see Deep Dive."
    },
    {
      "id": "hotd-s3",
      "title": "House of the Dragon — Season 3",
      "type": "TV",
      "releaseDate": "2026-06-21",
      "releaseWindow": "Airing now (Jun 21 – Aug 9, 2026)",
      "dateConfirmed": true,
      "platform": "HBO / HBO Max",
      "producers": ["HBO", "Ryan Condal", "George R.R. Martin"],
      "rightsHolder": "Warner Bros. Discovery Global Consumer Products",
      "franchise": "Game of Thrones universe",
      "genre": "Fantasy drama",
      "keywords": ["House of the Dragon", "Team Black", "Team Green", "Targaryen", "Daemon Targaryen"],
      "scores": { "scale": 8, "reachability": 8, "merchability": 8, "passion": 8, "competition": 5 },
      "monthSpotlight": true,
      "episodes": { "start": "2026-06-21", "cadenceDays": 7, "count": 8, "night": "Sunday" },
      "notes": "Mid-season right now with weekly Sunday episodes through Aug 9. House sigils, Team Black/Team Green, and dragon iconography are proven sellers with moderate saturation — the month's best whitespace-adjusted play."
    },
    {
      "id": "practical-magic-2",
      "title": "Practical Magic 2",
      "type": "Movie",
      "releaseDate": "2026-09-18",
      "releaseWindow": "September 18, 2026",
      "dateConfirmed": true,
      "platform": "Theatrical (Warner Bros.)",
      "producers": ["Warner Bros.", "Di Novi Pictures"],
      "rightsHolder": "Warner Bros. Discovery Global Consumer Products",
      "franchise": "Practical Magic",
      "genre": "Fantasy romance",
      "keywords": ["Practical Magic", "witchy aesthetic", "midnight margaritas", "cottagecore witch"],
      "scores": { "scale": 5, "reachability": 7, "merchability": 7, "passion": 7, "competition": 8 },
      "monthSpotlight": false,
      "notes": "Sleeper candidate: nostalgic female-skewing fandom, strong 'witchy lifestyle' aesthetic (candles, kitchen, apothecary), almost no existing licensed product, and a fall/Halloween release window."
    },
    {
      "id": "hunger-games-sotr",
      "title": "The Hunger Games: Sunrise on the Reaping",
      "type": "Movie",
      "releaseDate": "2026-11-20",
      "releaseWindow": "November 20, 2026",
      "dateConfirmed": true,
      "platform": "Theatrical (Lionsgate)",
      "producers": ["Lionsgate", "Color Force", "Nina Jacobson"],
      "rightsHolder": "Lionsgate consumer products / licensing",
      "franchise": "The Hunger Games",
      "genre": "Dystopian action",
      "keywords": ["Hunger Games", "Sunrise on the Reaping", "Haymitch", "mockingjay", "District 12"],
      "scores": { "scale": 8, "reachability": 8, "merchability": 7, "passion": 8, "competition": 6 },
      "monthSpotlight": false,
      "notes": "Haymitch prequel from the #1 bestselling 2025 novel. Mockingjay iconography is instantly recognizable and the licensed shelf has thinned since the original films — strong holiday-quarter play."
    },
    {
      "id": "narnia-gerwig",
      "title": "The Chronicles of Narnia (Greta Gerwig)",
      "type": "Movie",
      "releaseDate": "2026-11-26",
      "releaseWindow": "Nov 26, 2026 (IMAX), Netflix at Christmas",
      "dateConfirmed": true,
      "platform": "IMAX + Netflix",
      "producers": ["Netflix", "The Mark Gordon Company", "Greta Gerwig"],
      "rightsHolder": "Netflix Consumer Products (with the C.S. Lewis Company)",
      "franchise": "The Chronicles of Narnia",
      "genre": "Fantasy",
      "keywords": ["Narnia", "Aslan", "wardrobe", "The Magician's Nephew"],
      "scores": { "scale": 7, "reachability": 7, "merchability": 6, "passion": 7, "competition": 7 },
      "monthSpotlight": false,
      "notes": "Dormant franchise rebooted by an A-list director; existing Narnia product is nearly nonexistent, giving early movers room if the film hits."
    },
    {
      "id": "avengers-doomsday",
      "title": "Avengers: Doomsday",
      "type": "Movie",
      "releaseDate": "2026-12-18",
      "releaseWindow": "December 18, 2026",
      "dateConfirmed": true,
      "platform": "Theatrical (Disney / Marvel)",
      "producers": ["Marvel Studios", "Kevin Feige"],
      "rightsHolder": "Disney Consumer Products",
      "franchise": "Marvel Cinematic Universe",
      "genre": "Superhero event",
      "keywords": ["Avengers Doomsday", "Doctor Doom", "Robert Downey Jr Doom", "MCU"],
      "scores": { "scale": 10, "reachability": 7, "merchability": 9, "passion": 9, "competition": 2 },
      "monthSpotlight": false,
      "notes": "Biggest scale event of the window (RDJ as Doctor Doom), but Marvel licensing saturation means opportunity concentrates in official licensee resale and Doom-specific novelty."
    },
    {
      "id": "dune-part-three",
      "title": "Dune: Part Three",
      "type": "Movie",
      "releaseDate": "2026-12-18",
      "releaseWindow": "December 18, 2026",
      "dateConfirmed": true,
      "platform": "Theatrical (Warner Bros. / Legendary)",
      "producers": ["Legendary Pictures", "Denis Villeneuve", "Mary Parent"],
      "rightsHolder": "Warner Bros. Discovery Global Consumer Products / Legendary",
      "franchise": "Dune",
      "genre": "Sci-fi epic",
      "keywords": ["Dune Part Three", "Arrakis", "Atreides", "Lisan al Gaib", "sandworm"],
      "scores": { "scale": 7, "reachability": 8, "merchability": 6, "passion": 8, "competition": 6 },
      "monthSpotlight": false,
      "notes": "Head-to-head with Doomsday on the same date (one may move). Unique, ownable keyword universe (Arrakis, sandworms) and an under-served adult fandom."
    },
    {
      "id": "harry-potter-s1",
      "title": "Harry Potter — Season 1 (HBO series)",
      "type": "TV",
      "releaseDate": "2026-12-25",
      "releaseWindow": "December 25, 2026",
      "dateConfirmed": true,
      "platform": "HBO / HBO Max",
      "producers": ["HBO", "Warner Bros. Television", "David Heyman", "Francesca Gardiner"],
      "rightsHolder": "Warner Bros. Discovery Global Consumer Products",
      "franchise": "Wizarding World",
      "genre": "Fantasy",
      "keywords": ["Harry Potter series", "Hogwarts", "house colors", "wizarding world", "Gryffindor Slytherin"],
      "scores": { "scale": 10, "reachability": 9, "merchability": 10, "passion": 9, "competition": 2 },
      "monthSpotlight": false,
      "notes": "Christmas Day premiere. The single largest merch property of the window — house-branded product is a proven evergreen — but the shelf is deeply saturated; new-cast character product is where fresh demand will form."
    },
    {
      "id": "percy-jackson-s3",
      "title": "Percy Jackson and the Olympians — Season 3",
      "type": "TV",
      "releaseDate": "2026-12-12",
      "releaseWindow": "December 2026 (reports conflict on exact date)",
      "dateConfirmed": false,
      "platform": "Disney+",
      "producers": ["20th Television", "Disney Branded Television", "Rick Riordan"],
      "rightsHolder": "Disney Consumer Products",
      "franchise": "Percy Jackson / Camp Half-Blood",
      "genre": "Fantasy adventure",
      "keywords": ["Percy Jackson", "Camp Half-Blood", "Titan's Curse", "demigod"],
      "scores": { "scale": 6, "reachability": 7, "merchability": 6, "passion": 7, "competition": 7 },
      "monthSpotlight": false,
      "notes": "Camp Half-Blood tees/hoodies are the franchise's proven item and official supply is thin — a mid-size but reliable teen/YA play."
    },
    {
      "id": "ice-age-boiling-point",
      "title": "Ice Age: Boiling Point",
      "type": "Movie",
      "releaseDate": "2027-02-05",
      "releaseWindow": "February 5, 2027",
      "dateConfirmed": false,
      "platform": "Theatrical (Disney / 20th Century)",
      "producers": ["20th Century Animation"],
      "rightsHolder": "Disney Consumer Products",
      "franchise": "Ice Age",
      "genre": "Animated comedy",
      "keywords": ["Ice Age", "Scrat", "Sid the sloth"],
      "scores": { "scale": 7, "reachability": 6, "merchability": 6, "passion": 5, "competition": 5 },
      "monthSpotlight": false,
      "notes": "First theatrical Ice Age in a decade; nostalgia-driven family property with moderate merch pull (Scrat novelty leads)."
    },
    {
      "id": "fallout-s3",
      "title": "Fallout — Season 3",
      "type": "TV",
      "releaseDate": "2027-06-01",
      "releaseWindow": "June 2027 (expected)",
      "dateConfirmed": false,
      "platform": "Prime Video",
      "producers": ["Kilter Films", "Jonathan Nolan", "Lisa Joy", "Bethesda"],
      "rightsHolder": "Bethesda Softworks (Microsoft) — game publisher controls merchandising",
      "franchise": "Fallout",
      "genre": "Post-apocalyptic sci-fi",
      "keywords": ["Fallout show", "Vault Boy", "Nuka Cola", "Vault-Tec", "New Vegas"],
      "scores": { "scale": 7, "reachability": 9, "merchability": 8, "passion": 8, "competition": 6 },
      "monthSpotlight": false,
      "notes": "In-universe brands (Vault-Tec, Nuka Cola, numbered vault suits) are ready-made product lines with highly ownable keywords; gaming+TV crossover fandom buys."
    },
    {
      "id": "wednesday-s3",
      "title": "Wednesday — Season 3",
      "type": "TV",
      "releaseDate": "2027-06-15",
      "releaseWindow": "Summer 2027 (expected, ~June)",
      "dateConfirmed": false,
      "platform": "Netflix",
      "producers": ["MGM Television", "Tim Burton", "Alfred Gough", "Miles Millar"],
      "rightsHolder": "Netflix Consumer Products (with Amazon MGM / Tee & Charles Addams Foundation)",
      "franchise": "The Addams Family",
      "genre": "Supernatural comedy",
      "keywords": ["Wednesday Addams", "Nevermore Academy", "Enid", "Thing"],
      "scores": { "scale": 9, "reachability": 8, "merchability": 9, "passion": 8, "competition": 4 },
      "monthSpotlight": false,
      "notes": "Netflix's biggest series; Nevermore Academy collegiate-style apparel and goth-adjacent fashion travel far beyond the show's airdates."
    },
    {
      "id": "atla-s2",
      "title": "Avatar: The Last Airbender — Season 2",
      "type": "TV",
      "releaseDate": "2026-11-15",
      "releaseWindow": "Late 2026 (expected)",
      "dateConfirmed": false,
      "platform": "Netflix",
      "producers": ["Netflix", "Rideback"],
      "rightsHolder": "Paramount Consumer Products (Nickelodeon owns the underlying IP)",
      "franchise": "Avatar: The Last Airbender",
      "genre": "Fantasy adventure",
      "keywords": ["Avatar Last Airbender", "four nations", "Appa", "Zuko", "bending"],
      "scores": { "scale": 7, "reachability": 8, "merchability": 8, "passion": 8, "competition": 6 },
      "monthSpotlight": false,
      "notes": "Four-nations emblems and Appa plush are evergreen sellers; live-action season renews demand against a moderately stocked shelf."
    },
    {
      "id": "stranger-things-tales-85",
      "title": "Stranger Things: Tales From '85",
      "type": "TV",
      "releaseDate": "2026-10-01",
      "releaseWindow": "2026 (expected)",
      "dateConfirmed": false,
      "platform": "Netflix (animated)",
      "producers": ["Upside Down Pictures", "The Duffer Brothers", "Flying Bark Productions"],
      "rightsHolder": "Netflix Consumer Products",
      "franchise": "Stranger Things",
      "genre": "Animated sci-fi horror",
      "keywords": ["Stranger Things animated", "Hawkins", "Demogorgon", "Hellfire Club"],
      "scores": { "scale": 7, "reachability": 7, "merchability": 7, "passion": 7, "competition": 5 },
      "monthSpotlight": false,
      "notes": "First spinoff after the flagship's Dec 2025 finale; retro-80s animation style opens a fresh art direction for product while the fandom is still hot."
    },
    {
      "id": "the-madison",
      "title": "The Madison (Yellowstone universe)",
      "type": "TV",
      "releaseDate": "2026-09-15",
      "releaseWindow": "2026 (expected)",
      "dateConfirmed": false,
      "platform": "Paramount+",
      "producers": ["101 Studios", "MTV Entertainment Studios", "Taylor Sheridan"],
      "rightsHolder": "Paramount Consumer Products",
      "franchise": "Yellowstone universe",
      "genre": "Family drama (Montana)",
      "keywords": ["The Madison show", "Yellowstone spinoff", "Montana ranch style", "western lifestyle"],
      "scores": { "scale": 6, "reachability": 6, "merchability": 7, "passion": 6, "competition": 7 },
      "monthSpotlight": false,
      "notes": "Yellowstone proved ranch-lifestyle branding (Dutton Ranch) outsells character merch. The Madison's NYC-to-Montana premise may repeat the playbook for a female-skewing audience."
    },
    {
      "id": "spider-noir",
      "title": "Marvel's Spider-Noir",
      "type": "TV",
      "releaseDate": "2026-08-15",
      "releaseWindow": "2026 (expected)",
      "dateConfirmed": false,
      "platform": "Prime Video / MGM+",
      "producers": ["Sony Pictures Television", "Amazon MGM Studios", "Oren Uziel"],
      "rightsHolder": "Disney Consumer Products (Marvel controls Spider-Man merchandising)",
      "franchise": "Marvel / Spider-Man",
      "genre": "Noir superhero",
      "keywords": ["Spider-Noir", "Nicolas Cage Spider-Man", "noir comics"],
      "scores": { "scale": 6, "reachability": 7, "merchability": 7, "passion": 7, "competition": 7 },
      "monthSpotlight": false,
      "notes": "Nicolas Cage in a 1930s monochrome Spider-verse — a distinctive art style with almost no dedicated product; cult-hit potential."
    },
    {
      "id": "shrek-5",
      "title": "Shrek 5",
      "type": "Movie",
      "releaseDate": "2027-06-30",
      "releaseWindow": "June 30, 2027",
      "dateConfirmed": true,
      "platform": "Theatrical (Universal / DreamWorks)",
      "producers": ["DreamWorks Animation"],
      "rightsHolder": "Universal Products & Experiences",
      "franchise": "Shrek",
      "genre": "Animated comedy",
      "keywords": ["Shrek 5", "Shrek meme", "swamp", "Donkey"],
      "scores": { "scale": 9, "reachability": 8, "merchability": 8, "passion": 8, "competition": 6 },
      "monthSpotlight": false,
      "notes": "Moved out of Dec 2026 to avoid Doomsday. Gen-Z meme culture has kept Shrek demand alive for a decade with relatively little fresh official product — unusual whitespace for a franchise this big."
    }
  ]
};
if (typeof module !== "undefined") { module.exports = ENTERTAINMENT_DATA; }
